version: "3.8"

services:
  node:
      container_name: create-reactapp
      image: "node:14"
      tty: true
      volumes:
          - ../:/usr/src/app
      working_dir: /usr/src/app
      ports:
            - 3000:3000
      
